# Generated by Django 6.0.5 on 2026-05-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_creado_en_tienda_creada_en_and_more'),
    ]

    operations = [
    ]
