# Generated by Django 6.0.5 on 2026-05-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_fix_nota_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ocasion_regalo',
            field=models.CharField(blank=True, choices=[('todos', 'Todas las ocasiones'), ('cumpleanos', 'Cumpleaños'), ('amor', 'Amor y Amistad'), ('navidad', 'Navidad'), ('halloween', 'Halloween')], default='todos', max_length=20),
        ),
    ]
