# Generated by Django 6.0.5 on 2026-05-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_producto_ocasion_regalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='es_regalo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='regalo_decoracion',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='regalo_envoltura',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='regalo_mensaje',
            field=models.TextField(blank=True, default=''),
        ),
    ]
