# Generated by Django 6.0.5 on 2026-05-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_regalo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('', 'Sin categoría'), ('Maquillaje', 'Maquillaje'), ('Ropa y Accesorios', 'Ropa y Accesorios'), ('Carteras y Bolsos', 'Carteras y Bolsos'), ('Calzado', 'Calzado'), ('Papelería', 'Papelería'), ('Tecnología', 'Tecnología'), ('Regalos', 'Regalos'), ('Joyería', 'Joyería'), ('Artesanías', 'Artesanías')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='seccion_landing',
            field=models.CharField(blank=True, choices=[('', 'No aparece en landing'), ('nuevos', 'Nuevos Productos'), ('destacados', 'Más Vendidos'), ('region', 'Productos de la Región')], default='', max_length=20),
        ),
    ]
