# Generated by Django 6.0.5 on 2026-05-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_add_categoria_to_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='0 = primero')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen de fondo del slide', upload_to='banners/')),
                ('activo', models.BooleanField(default=True)),
                ('editado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Landing',
                'verbose_name_plural': 'Banners Landing',
                'ordering': ['orden'],
            },
        ),
    ]
