# Generated by Django 6.0.5 on 2026-05-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerlanding',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='bannerlanding',
            name='subtitulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bannerlanding',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bannerlanding',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='bannerlanding',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
