# Generated by Django 6.0.5 on 2026-05-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_bannerlanding_options_bannerlanding_subtitulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerlanding',
            options={'ordering': ['orden'], 'verbose_name': 'Banner Landing', 'verbose_name_plural': 'Banners Landing'},
        ),
        migrations.AddField(
            model_name='bannerlanding',
            name='color_fondo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bannerlanding',
            name='texto_boton',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
